version: '3.8'

services:
  my_postgres_db:
    image: postgres:latest
    container_name: postgres-san
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: san_db
    ports:
      - "5430:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  my-san-service:
    depends_on:
      - my_postgres_db
    build:
      context: .
      dockerfile: Dockerfile
    image: 'my-san-service-iso'
    container_name: 'my-san-service-container'
    environment:
      DB_HOST: my_postgres_db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: test123
      DB_NAME: san_db
    ports:
      - "8888:8080"
    volumes:
      - ./internal/database/migrations:/app/internal/database/migrations
volumes:
  pg_data:
